#!/usr/bin/env python
# -*- coding: utf-8 -*-

from hachoir_wx.app import app_t
from hachoir_core.cmd_line import (getHachoirOptions,
    configureHachoir, unicodeFilename)
from optparse import OptionGroup, OptionParser

def parseOptions():
    parser = OptionParser(usage="%prog [options] [filename]")

#    common = OptionGroup(parser, "Urwid", _("Option of hachoir-wx"))
#    common.add_option(...)
#    parser.add_option_group(common)

    hachoir = getHachoirOptions(parser)
    parser.add_option_group(hachoir)

    values, arguments = parser.parse_args()
    if len(arguments) == 1:
        filename = arguments[0]
    elif not arguments:
        filename =  None
    else:
        parser.print_help()
        sys.exit(1)
    return values, filename

def main():
    values, filename = parseOptions()
    configureHachoir(values)
    if filename:
        app = app_t(unicodeFilename(filename), filename)
    else:
        app = app_t()
    app.MainLoop()

if __name__ == '__main__':
    main()
